### ISSUE TITLE
Lab 16 - syntax error

### ISSUE THREAD

**Issue by gscoffield** [jofraley/Hacking_JavaScript#12]
In step 3, it says:
// Add widget to the UI
view.ui.add(searchWidget, "top-right");

It needs to be:
view.ui.add(search, "top-right");

**Comment by jofraley** [comment]
OMG, look at you!!!  Using github even!!!  Have a great weekend!

Sent from my iPhone

On Dec 9, 2016, at 4:16 PM, Gary Scoffield <notifications@github.com<mailto:notifications@github.com>> wrote:


In step 3, it says:
// Add widget to the UI
view.ui.add(searchWidget, "top-right");

It needs to be:
view.ui.add(search, "top-right");

**Comment by jofraley** [comment]
fixed the syntax error on Lab 16.
