### ISSUE TITLE
Lab 4: Style Feature Layer - Solution contains code for building Search tool

### ISSUE THREAD

**Issue by pshowalter** [jofraley/Hacking_JavaScript#4]
Solution contains code for building Search metro station tool, but not explained or suggested in the lab portion of the exercise.

If using the solution for the first part of the Lab, user might be confused with the code for the Optional sections.  It is even more complicated with the Search and Popup Template, which are not mentioned in the lab.

**Comment by jofraley** [comment]
@pshowalter Thanks for point that out, I updated and removed the search from this exercise.
