### ISSUE TITLE
Missing pop-up code in lesson 15 - Style a Layer Popup

### ISSUE THREAD

**Issue by gscoffield** [jofraley/Hacking_JavaScript#8]
I think the pop-up code is missing in Lesson 15 to make sure it pops-up in one place:
	  var view = new MapView({
         container: "viewDiv",
         map: map,
         center: [-77.029, 38.89],
         zoom: 10,
	 popup: {
 	   dockEnabled: true,
           dockOptions: {
	     buttonEnabled: false,
	     position: "bottom-right",
	     breakpoint: false
	   }
	 }
       });

I pulled this code from your finished code sample, but I don't see all the pop-up stuff in the lesson.

**Comment by jofraley** [comment]
The final code includes the code for the bonus to show you how it is done.  So when you finish just the exercise you will only have a popup when you click on the map.
